name: Tag and Release

on:
  workflow_dispatch:
    inputs:
      rancher_branch:
        required: true
        default: "main"
      tag_prefix:
        required: true
        default: "v1.0"

permissions:
  contents: write

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
    - name : Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        fetch-depth: 0

    - name: Compute next tag
      id: tag
      run: |
        git tag
        latest_patch=$(git tag | grep "^$PREFIX\." | sed "s|$PREFIX\.||" | sort -n | tail -n 1)
        latest_tag=$PREFIX.$latest_patch
        # If latest is already at HEAD, then we don't need to create it
        if git tag --points-at HEAD | grep -c "$latest_tag"; then
          echo "Tag $latest_tag already is already on latest commit, no need to create a new tag"
          echo "tag=$latest_tag" >> $GITHUB_OUTPUT
          echo "needs_create=true" >> $GITHUB_OUTPUT
        else
          echo "Tag $latest_tag is on older commit, will create a new tag"
          new_patch=$((latest_patch+1))
          echo "tag=$PREFIX.$new_patch" >> $GITHUB_OUTPUT
          echo "needs_create=false" >> $GITHUB_OUTPUT
        fi
      env:
        PREFIX: ${{ github.event.inputs.tag_prefix }}

    - name: Create Tag
      if: ${{ steps.tag.outputs.needs_create == 'true' }}
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.tag.outputs.tag }}',
              sha: context.sha
          })
