name: Tag and Release

on:
  workflow_dispatch:
    inputs:
      rancher_ref:
        required: true
        default: "main"
      tag_prefix:
        required: true
        default: "v1.0"

permissions:
  contents: write

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
    - name : Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        fetch-depth: 0

    - name: Compute tag
      id: tag
      run: |
        git tag
        latest_patch=$(git tag | grep "^$PREFIX\." | sed "s|$PREFIX\.||" | sort -n | tail -n 1)
        latest_tag=$PREFIX.$latest_patch
        # If latest is already at HEAD, then we don't need to create it
        if git tag --points-at HEAD | grep -c "$latest_tag"; then
          echo "Tag $latest_tag already is already on latest commit, no need to create a new tag"
          echo "tag=$latest_tag" >> $GITHUB_OUTPUT
          echo "needs_create=false" >> $GITHUB_OUTPUT
        else
          echo "Tag $latest_tag is on older commit, will create a new tag"
          new_patch=$((latest_patch+1))
          echo "tag=$PREFIX.$new_patch" >> $GITHUB_OUTPUT
          echo "needs_create=true" >> $GITHUB_OUTPUT
        fi
      env:
        PREFIX: ${{ github.event.inputs.tag_prefix }}

    - name: Create Tag
      if: ${{ steps.tag.outputs.needs_create == 'true' }}
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.tag.outputs.tag }}',
              sha: context.sha
          })

    - name: Checkout rancher repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      with:
        repository: ${{ github.repository_owner }}/rancher-rancher
        ref: "${{ github.event.inputs.rancher_ref }}"
        token: ${{ secrets.GH_TOKEN }}
        path: rancher
        # Allow making git push request later on
        persist-credentials: true

    - name: Bump steve and push
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        TAG: ${{ steps.tag.outputs.tag }}
        RANCHER_REF: ${{ github.event.inputs.rancher_ref }}
      run: |
        cd rancher

        BRANCH="bump-webhook-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}"
        git checkout -b "$BRANCH"

        echo go mod edit -require=github.com/rancher/steve@$TAG
        echo go mod tidy
        echo go generate ./...
        echo $TAG >> hi.txt
        git add .
        git commit -m "Bump steve to $TAG"

        git push origin $BRANCH

        gh pr create \
          --title "[$RANCHER_REF] Bump steve to $TAG" \
          --repo ${{ github.repository_owner }}/rancher-rancher \
          --head "${{ github.repository_owner }}:$BRANCH" \
          --base "$RANCHER_REF"
